# Generated by Django 4.0.3 on 2022-03-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('releaseDate', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=5)),
                ('sizeCountry', models.CharField(max_length=10)),
                ('washingType', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fitType', models.CharField(max_length=10)),
                ('closureType', models.CharField(max_length=10)),
                ('dimensions', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('waist', models.CharField(max_length=10)),
                ('frontRise', models.CharField(max_length=10)),
                ('backRise', models.CharField(max_length=10)),
                ('upperThigh', models.CharField(max_length=10)),
                ('inseam', models.CharField(max_length=10)),
                ('legOpening', models.CharField(max_length=10)),
                ('pocketNumber', models.IntegerField()),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('pocketNumber', models.IntegerField()),
                ('moistureWicking', models.BooleanField()),
                ('breathable', models.BooleanField()),
                ('type', models.CharField(max_length=10)),
                ('inseam', models.CharField(max_length=10)),
                ('outseam', models.CharField(max_length=10)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('tagFree', models.BooleanField()),
                ('layFlat', models.BooleanField()),
                ('sleeveHem', models.CharField(max_length=10)),
                ('moistureWicking', models.BooleanField()),
                ('tapedNeck', models.BooleanField()),
                ('bottomHem', models.CharField(max_length=10)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('forSale', models.BooleanField()),
                ('inventory', models.IntegerField()),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='clothes')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
    ]
