# Generated by Django 4.0.3 on 2022-03-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('wattage', models.CharField(max_length=10)),
                ('technologies', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BluetoothTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CameraFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChargerTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FrontCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=100)),
                ('features', models.ManyToManyField(to='mobilephone.camerafeature')),
            ],
        ),
        migrations.CreateModel(
            name='GpsTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeadphoneTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designType', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('releaseDate', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('speaker', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('battery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.battery')),
                ('frontCamera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.frontcamera')),
            ],
        ),
        migrations.CreateModel(
            name='OsCpuGpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=30)),
                ('cpu', models.CharField(max_length=30)),
                ('cpuDescription', models.CharField(max_length=256)),
                ('gpu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('diagonal', models.CharField(max_length=10)),
                ('refreshRate', models.CharField(max_length=10)),
                ('brightness', models.CharField(max_length=30)),
                ('glass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=10)),
                ('internalMem', models.CharField(max_length=10)),
                ('internalMemAvail', models.CharField(max_length=10)),
                ('memoryCard', models.CharField(default='', max_length=100)),
                ('contacts', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WifiTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advancedSecurities', models.CharField(max_length=256)),
                ('resistances', models.CharField(max_length=50)),
                ('recorder', models.CharField(max_length=50)),
                ('audioFormats', models.ManyToManyField(to='mobilephone.audioformat')),
                ('specialFeatures', models.ManyToManyField(to='mobilephone.specialfeature')),
                ('videoFormats', models.ManyToManyField(to='mobilephone.videoformat')),
            ],
        ),
        migrations.CreateModel(
            name='RearCameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=100)),
                ('flash', models.BooleanField(default=True)),
                ('features', models.ManyToManyField(to='mobilephone.camerafeature')),
                ('recordingRes', models.ManyToManyField(to='mobilephone.recordingresolution')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='mobilephone/')),
                ('mobilePhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.mobilephone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellularNetwork', models.CharField(max_length=30)),
                ('sim', models.CharField(max_length=256)),
                ('others', models.CharField(max_length=256)),
                ('bluetooth', models.ManyToManyField(to='mobilephone.bluetoothtech')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.chargertech')),
                ('gps', models.ManyToManyField(to='mobilephone.gpstech')),
                ('headphone', models.ManyToManyField(to='mobilephone.headphonetech')),
                ('wifi', models.ManyToManyField(to='mobilephone.wifitech')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('forSale', models.BooleanField()),
                ('inventory', models.IntegerField()),
                ('mobilePhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.mobilephone')),
            ],
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='osCpuGpu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.oscpugpu'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='phoneConnections',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.phoneconnections'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='phoneScreen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.phonescreen'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='phoneStorage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.phonestorage'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='rearCameras',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.rearcameras'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='utilities',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.utilities'),
        ),
        migrations.AddField(
            model_name='frontcamera',
            name='recordingRes',
            field=models.ManyToManyField(to='mobilephone.recordingresolution'),
        ),
    ]
