# Generated by Django 4.0.3 on 2022-03-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilephone', '0002_rename_wattage_battery_maxwattage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontcamera',
            old_name='features',
            new_name='frontFeatures',
        ),
        migrations.RenameField(
            model_name='frontcamera',
            old_name='recordingRes',
            new_name='frontRecordingRes',
        ),
        migrations.RenameField(
            model_name='frontcamera',
            old_name='resolution',
            new_name='frontResolution',
        ),
        migrations.RenameField(
            model_name='rearcameras',
            old_name='features',
            new_name='rearFeatures',
        ),
        migrations.RenameField(
            model_name='rearcameras',
            old_name='recordingRes',
            new_name='rearRecordingRes',
        ),
        migrations.RenameField(
            model_name='rearcameras',
            old_name='resolution',
            new_name='rearResolution',
        ),
        migrations.RenameField(
            model_name='recordingresolution',
            old_name='resolution',
            new_name='recordResolution',
        ),
    ]
