# Generated by Django 4.0.3 on 2022-03-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=20)),
                ('releaseDate', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimensions', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hairdryer',
            fields=[
                ('electronics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electronics.electronics')),
                ('hairType', models.CharField(max_length=10)),
                ('wattage', models.CharField(max_length=10)),
                ('voltage', models.CharField(max_length=10)),
                ('speedSettings', models.IntegerField()),
                ('heatSettings', models.IntegerField()),
            ],
            bases=('electronics.electronics',),
        ),
        migrations.CreateModel(
            name='ElectronicsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('forSale', models.BooleanField()),
                ('inventory', models.IntegerField()),
                ('electronics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.electronics')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='electronics')),
                ('electronics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.electronics')),
            ],
        ),
    ]
