# Generated by Django 4.0.3 on 2022-03-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sizeCountry', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('releaseDate', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=10)),
                ('upperMaterial', models.CharField(max_length=20)),
                ('soleMaterial', models.CharField(max_length=20)),
                ('liningMaterial', models.CharField(max_length=20)),
                ('dimensions', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessShoes',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('heelHeight', models.CharField(max_length=10)),
                ('heelMeasure', models.CharField(max_length=10)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='RunningShoes',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('nightReflect', models.BooleanField(default=True)),
                ('durability', models.CharField(max_length=10)),
                ('shockAbsorb', models.BooleanField(default=True)),
                ('ventilation', models.CharField(max_length=10)),
                ('ankleSupport', models.BooleanField(default=True)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('nightReflect', models.BooleanField(default=True)),
                ('heelHeight', models.CharField(max_length=10)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='ShoesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('forSale', models.BooleanField()),
                ('inventory', models.IntegerField()),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='ShoesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='shoes/')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoes')),
            ],
        ),
    ]
