# Generated by Django 4.0.3 on 2022-03-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu', models.CharField(max_length=50)),
                ('soundTechnologies', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('baseSpeed', models.CharField(max_length=10)),
                ('maxSpeed', models.CharField(max_length=10)),
                ('l3Cache', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=256)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('batteryCapacity', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=10)),
                ('releaseDate', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('audioVideo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laptop.audiovideo')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.cpu')),
                ('dimensions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laptop.dimensions')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.CharField(max_length=10)),
                ('resolution', models.CharField(max_length=10)),
                ('refreshRate', models.CharField(max_length=10)),
                ('technology', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramSize', models.CharField(max_length=10)),
                ('ramType', models.CharField(max_length=10)),
                ('busRamSpeed', models.CharField(max_length=10)),
                ('maxSize', models.CharField(max_length=30)),
                ('secondary', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('forSale', models.BooleanField()),
                ('inventory', models.IntegerField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptop')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopInterfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wirelessConnection', models.CharField(max_length=50)),
                ('webcam', models.CharField(max_length=20)),
                ('features', models.CharField(max_length=100)),
                ('keyboardLight', models.BooleanField()),
                ('interfaces', models.ManyToManyField(to='laptop.physicalinterface')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='laptop/')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptop')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptopInterfaces',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptopinterfaces'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptopScreen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptopscreen'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptopStorage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptopstorage'),
        ),
    ]
