# Generated by Django 4.0.3 on 2022-03-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoundTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='laptopinterfaces',
            name='features',
        ),
        migrations.AddField(
            model_name='dimensions',
            name='material',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='bundledSoftwares',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='laptopinterfaces',
            name='memoryCard',
            field=models.CharField(default='Micro SD', max_length=50),
        ),
        migrations.AddField(
            model_name='laptopscreen',
            name='touchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audiovideo',
            name='gpu',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='audiovideo',
            name='soundTechnologies',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='batteryCapacity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptopinterfaces',
            name='keyboardLight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laptopinterfaces',
            name='webcam',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='laptopinterfaces',
            name='wirelessConnection',
        ),
        migrations.AlterField(
            model_name='laptopscreen',
            name='resolution',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='laptopscreen',
            name='technology',
        ),
        migrations.AlterField(
            model_name='laptopstorage',
            name='maxSize',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptopstorage',
            name='ramType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicalinterface',
            name='interface',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='laptopinterfaces',
            name='otherFeat',
            field=models.ManyToManyField(to='laptop.otherfeatures'),
        ),
        migrations.AddField(
            model_name='audiovideo',
            name='soundTechnologies',
            field=models.ManyToManyField(to='laptop.soundtech'),
        ),
        migrations.AddField(
            model_name='laptopinterfaces',
            name='wirelessConnection',
            field=models.ManyToManyField(to='laptop.wirelesstech'),
        ),
        migrations.AddField(
            model_name='laptopscreen',
            name='technology',
            field=models.ManyToManyField(to='laptop.screentechnology'),
        ),
    ]
