# Generated by Django 4.0.3 on 2022-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_otherfeatures_screentechnology_soundtech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
