# Generated by Django 4.0.3 on 2022-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_alter_laptop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='baseSpeed',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='l3Cache',
            field=models.CharField(max_length=30),
        ),
    ]
