# Generated by Django 4.0.3 on 2022-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0004_alter_cpu_basespeed_alter_cpu_l3cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='family',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
