# Generated by Django 4.0.3 on 2022-04-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_cpu_family_alter_cpu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='name',
            new_name='cpuName',
        ),
    ]
